### ISSUE TITLE
spark-bigquery/counts_by_subreddit.py /

### ISSUE THREAD

**Issue by sk-haghighi** [GoogleCloudDataproc/cloud-dataproc#139]
Could you please let me know why when I run the scripts it returns a Null table. The table is empty without any records. Also why the table name starts with "f" (table = f"fh-bigquery.reddit_posts.{year}_{month}"?
Thank you very much.

**Comment by Gaurangi94** [comment]
Hello,

If you are referring to the f before the quotes, i.e. **f**"fh-bigquery.reddit_posts.{year}_{month}", it is for formatting since we are are constructing a string using other variables. Please note that this works only in Python3. For more information - https://realpython.com/python-f-strings/

As for the empty table, did you run backfill.sh in the same folder? Backfill.sh will create all the tables that counts_by_subreddit.py will read. If these tables don't exist, counts_by_subreddits.py will return empty results.

Also, please make sure you are using the latest version of spark-bigquery-connector, i.e. gs://spark-lib/bigquery/spark-bigquery-latest_2.12.jar
